{
 "title": "Axpert Gateway",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "serialno",
    "label": "Serial Number",
    "query": {
     "query": "label_values(axpert_battery_capacity_percent,serialno)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_devicemode{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Output Source Priority",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_output_sourcepriority{serialno=\"$serialno\"}",
     "legendFormat": "Line"
    }
   ]
  },
  {
   "title": "Charger Source Priority",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_charger_sourcepriority{serialno=\"$serialno\"}",
     "legendFormat": "Line"
    }
   ]
  },
  {
   "title": "Charge Source",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axpert_acchargeon", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_lineloss{serialno=\"$serialno\"}",
     "legendFormat": "Line"
    }
   ]
  },
  {
   "title": "Load Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_loadon{serialno=\"$serialno\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Overload Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_overload{serialno=\"$serialno\"}",
     "legendFormat": "Overload"
    }
   ]
  },
  {
   "title": "Device Mode",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "axpert_devicemode{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Output Source Priority",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "targets": [
    { "expr": "axpert_output_sourcepriority", "legendFormat": " " }
   ]
  },
  {
   "title": "Charger Source Priority",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "axpert_charger_sourcepriority{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Charge Source",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "axpert_acchargeon{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Grid Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "axpert_lineloss{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Load Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "axpert_loadon{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Overload Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "expr": "axpert_overload{serialno=\"$serialno\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Current Battery (%)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_battery_capacity_percent{serialno=\"$serialno\"}",
     "legendFormat": "Overload"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_battery_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Heatsink Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axpert_heatsink_temperature{serialno=\"$serialno\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Output Load (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axpert_output_load_percent", "legendFormat": "Load Percentage" }
   ]
  },
  {
   "title": "Max AC Charger Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axpert_charger_maxcurrent", "legendFormat": "Amps" }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "axpert_battery_capacity_percent{serialno=\"$serialno\"}",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "axpert_battery_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Voltage"
    },
    {
     "expr": "axpert_battery_recharge_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Recharge Voltage"
    },
    {
     "expr": "axpert_battery_redischarge_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Redischarge Voltage"
    },
    {
     "expr": "axpert_battery_float_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Float Voltage"
    },
    {
     "expr": "axpert_battery_cutoff_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Cutoff Voltage"
    }
   ]
  },
  {
   "title": "Battery Charge / Discharge Current",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "axpert_battery_charge_current{serialno=\"$serialno\"}",
     "legendFormat": "Charge Current"
    },
    {
     "expr": "axpert_battery_discharge_current{serialno=\"$serialno\"}",
     "legendFormat": "Discharge Current"
    }
   ]
  },
  { "title": "PV Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "PV Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "axpert_pvinput1_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Input 1"
    },
    {
     "expr": "axpert_pvinput2_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Input 2"
    },
    {
     "expr": "axpert_pvinput3_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Input 3"
    }
   ]
  },
  {
   "title": "PV Input Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "axpert_pvinput1_current{serialno=\"$serialno\"}",
     "legendFormat": "Input 1"
    },
    {
     "expr": "axpert_pvinput2_current{serialno=\"$serialno\"}",
     "legendFormat": "Input 2"
    },
    {
     "expr": "axpert_pvinput3_current{serialno=\"$serialno\"}",
     "legendFormat": "Input 3"
    }
   ]
  },
  { "title": "Grid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Grid Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "axpert_grid_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "axpert_grid_frequency{serialno=\"$serialno\"}",
     "legendFormat": "Frequency"
    }
   ]
  },
  { "title": "AC Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "AC Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "axpert_acoutput_voltage{serialno=\"$serialno\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "AC Output Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "axpert_acoutput_frequency{serialno=\"$serialno\"}",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "AC Output Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "axpert_acoutput_apparent_power{serialno=\"$serialno\"}",
     "legendFormat": "Apparent Power"
    }
   ]
  },
  {
   "title": "AC Output Active Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "axpert_acoutput_active_power{serialno=\"$serialno\"}",
     "legendFormat": "Active Power"
    }
   ]
  },
  {
   "title": "AC Output Load Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "axpert_output_load_percent{serialno=\"$serialno\"}",
     "legendFormat": "Load Percentage"
    }
   ]
  }
 ]
}